openapi: 3.0.0
info:
  title: Email Service API
  version: 1.0.0
paths:
  /api/contact/:
    post:
      summary: Recibir mensaje de contacto y enviar correo simulado
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name: { type: string }
                email: { type: string }
                message: { type: string }
      responses:
        "202":
          description: Mensaje encolado para env√≠o
